//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.04 at 12:11:53 AM EET 
//


package io.spring.guides.gs_producing_web_service;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the io.spring.guides.gs_producing_web_service package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: io.spring.guides.gs_producing_web_service
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetActivityResponse }
     * 
     */
    public GetActivityResponse createGetActivityResponse() {
        return new GetActivityResponse();
    }

    /**
     * Create an instance of {@link ActivityXsd }
     * 
     */
    public ActivityXsd createActivityXsd() {
        return new ActivityXsd();
    }

    /**
     * Create an instance of {@link GetMedicationPlanRequest }
     * 
     */
    public GetMedicationPlanRequest createGetMedicationPlanRequest() {
        return new GetMedicationPlanRequest();
    }

    /**
     * Create an instance of {@link GetRecommendationResponse }
     * 
     */
    public GetRecommendationResponse createGetRecommendationResponse() {
        return new GetRecommendationResponse();
    }

    /**
     * Create an instance of {@link GetCountryRequest }
     * 
     */
    public GetCountryRequest createGetCountryRequest() {
        return new GetCountryRequest();
    }

    /**
     * Create an instance of {@link GetRecommendationRequest }
     * 
     */
    public GetRecommendationRequest createGetRecommendationRequest() {
        return new GetRecommendationRequest();
    }

    /**
     * Create an instance of {@link GetLoginRequest }
     * 
     */
    public GetLoginRequest createGetLoginRequest() {
        return new GetLoginRequest();
    }

    /**
     * Create an instance of {@link GetMedicationPlanResponse }
     * 
     */
    public GetMedicationPlanResponse createGetMedicationPlanResponse() {
        return new GetMedicationPlanResponse();
    }

    /**
     * Create an instance of {@link MedicationPlanXsd }
     * 
     */
    public MedicationPlanXsd createMedicationPlanXsd() {
        return new MedicationPlanXsd();
    }

    /**
     * Create an instance of {@link GetCountryResponse }
     * 
     */
    public GetCountryResponse createGetCountryResponse() {
        return new GetCountryResponse();
    }

    /**
     * Create an instance of {@link Country }
     * 
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link GetLoginResponse }
     * 
     */
    public GetLoginResponse createGetLoginResponse() {
        return new GetLoginResponse();
    }

    /**
     * Create an instance of {@link PatientXsd }
     * 
     */
    public PatientXsd createPatientXsd() {
        return new PatientXsd();
    }

    /**
     * Create an instance of {@link GetActivityRequest }
     * 
     */
    public GetActivityRequest createGetActivityRequest() {
        return new GetActivityRequest();
    }

}
